### ISSUE TITLE
Github usernames with a hyphen in them cause alfred to return the help of the github command

### ISSUE THREAD

**Issue by zachfi** [hovsater/github.alfredextension#8]

**Comment by hovsater** [comment]
Is hyphens allowed in usernames? If so, can you give me an example?

Thanks for reporting the issue, I'll look into this matter if hyphens, indeed, are valid.

**Comment by zachfi** [comment]
Sure: https://github.com/puppetlabs-operations

Thank you.  Let me know if I can provide any more information.

**Comment by hovsater** [comment]
Thanks a lot @xaque208. I'll fix this issue as soon as possible. I'm over my head with work at the moment. Pull requests are welcome.
